[[redirects]]
from = "/api/*"
to = "https://:splat"
status = 200
force = true
headers = { ":scheme" = "https", "Accept-Encoding" = "gzip, deflate, br", "Accept-Language" = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6", "Origin" = "https://26994461492.gpt138.xyz", "Referer" = "https://26994461492.gpt138.xyz/", "Sec-Ch-Ua" = "\"Microsoft Edge\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\"", "Sec-Ch-Ua-Mobile" = "?0", "Sec-Ch-Ua-Platform" = "\"Windows\"", "Sec-Fetch-Dest" = "empty", "Sec-Fetch-Mode" = "cors", "Sec-Fetch-Site" = "cross-site", "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0" }