[[redirects]]
from = "/api/*"
to = "https://:splat"
status = 200
force = true
headers = { User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0", Origin = "https://8162403981.ai701.live", Referer = "https://8162403981.ai701.live/", Accept-Language = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6" }